version: '3.8'
services:
  client:
    image: node:20
    container_name: mern_client
    working_dir: /app
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install &&
               npm start"
    networks:
      - mern_network
    depends_on:
      - server

  server:
    image: node:20
    container_name: mern_server
    working_dir: /app
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DATABASE_URI=mongodb://db:27017/mern_database
    command: >
      bash -c "npm install &&
               npm start"
    networks:
      - mern_network
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: mern_db
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - db_data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  db_data: {}
  client_node_modules: {}
  server_node_modules: {}